// Auto-generated by Gulp
// Production Environment

export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: "",
    authDomain: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: "",
    clientId: ""
  },
  formsItemsApi: ""
  // Add other environment-specific variables here if needed
};
